name: Test & Lint

on:
  push:
    paths:
      - '**.go'
      - 'go.mod'
      - '.github/workflows/reviewdog.yml'
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - '.github/workflows/reviewdog.yml'

jobs:
  review-dog:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    name: Review Dog
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
      - run: go get
      - run: go generate ./...
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEW_DOG_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-review -runners=golint,govet